// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxuHFub8tjAdyP8-vP_ew0jVZ3KoMVz8',
    appId: '1:984973748142:web:43d4b02ebf453da4d58a3f',
    messagingSenderId: '984973748142',
    projectId: 'hajj-companion-app',
    authDomain: 'hajj-companion-app.firebaseapp.com',
    storageBucket: 'hajj-companion-app.firebasestorage.app',
    measurementId: 'G-PS26F3H2NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgL_SAMVTiZPZ4MdzQWrH6DnWoqmy6No',
    appId: '1:984973748142:android:9b398791c10b9e06d58a3f',
    messagingSenderId: '984973748142',
    projectId: 'hajj-companion-app',
    storageBucket: 'hajj-companion-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7n-Y1ZMEm7LEvCz70e-MUZ8k6Z0DENak',
    appId: '1:984973748142:ios:1bbd84c918c35351d58a3f',
    messagingSenderId: '984973748142',
    projectId: 'hajj-companion-app',
    storageBucket: 'hajj-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.hajjCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7n-Y1ZMEm7LEvCz70e-MUZ8k6Z0DENak',
    appId: '1:984973748142:ios:1bbd84c918c35351d58a3f',
    messagingSenderId: '984973748142',
    projectId: 'hajj-companion-app',
    storageBucket: 'hajj-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.hajjCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxuHFub8tjAdyP8-vP_ew0jVZ3KoMVz8',
    appId: '1:984973748142:web:96dd148b84863a0bd58a3f',
    messagingSenderId: '984973748142',
    projectId: 'hajj-companion-app',
    authDomain: 'hajj-companion-app.firebaseapp.com',
    storageBucket: 'hajj-companion-app.firebasestorage.app',
    measurementId: 'G-D0R9JXQ0KE',
  );
}
